language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t javelwilson/hooks-news -f Dockerfile.dev .

script:
  - docker run -e CI=true javelwilson/hooks-news npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "hooks-news"
  env: "HooksNews-env"
  bucket_name: "elasticbeanstalk-us-east-2-127596255715"
  bucket_path: "hooks-news"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

