FROM node:alpine
WORKDIR '/app'
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 3000
ENV FIREBASE_API_KEY FIREBASE_API_KEY
ENV FIREBASE_APP_ID FIREBASE_APP_ID
ENV FIREBASE_AUTH_DOMAIN FIREBASE_AUTH_DOMAIN
ENV FIREBASE_DATABASE_URL FIREBASE_DATABASE_URL
ENV FIREBASE_MEASUREMENT_ID FIREBASE_MEASUREMENT_ID
ENV FIREBASE_MESSAGING_SENDER_ID FIREBASE_MESSAGING_SENDER_ID
ENV FIREBASE_PROJECT_ID FIREBASE_PROJECT_ID
ENV FIREBASE_STORAGE_BUCKET FIREBASE_STORAGE_BUCKET
ENV NODE_ENV NODE_ENV
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=0 /app/build /usr/share/nginx/html